#!/usr/bin/env bash
hl_dir="$(dirname "$(readlink -f "$0")")" ## install_dir/bin
hl_dir="$(dirname "$hl_dir")" ## install_dir
g++ -w -I"$hl_dir/include" -Wl,-rpath,"$hl_dir/lib" -L"$hl_dir/lib" @INC_FLAGS@ @LIB_FLAGS@ -fopenmp -lHepLib -lginac -lcln -lqhullstatic_r -ljemalloc -lmpfr -lgmp $@ -lHepLib -lginac -lcln -lqhullstatic_r -ljemalloc -lmpfr -lgmp
# below without -ljemalloc
# g++ -w -I"$hl_dir/include" -Wl,-rpath,"$hl_dir/lib" -L"$hl_dir/lib" @INC_FLAGS@ @LIB_FLAGS@ -fopenmp -lHepLib -lginac -lcln -lqhullstatic_r -lmpfr -lgmp $@ -lHepLib -lginac -lcln -lqhullstatic_r -lmpfr -lgmp
