on:
  push:
    branches:
    - master

jobs:
  ubuntu-codecoverage:
    name: Ubuntu GCC, Code Coverage (x10)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4      
      - name: "build check"
        run: |
          ls
          sudo apt-get update
          sudo apt-get install wget
          sudo apt-get install gcc
          sudo apt-get install g++
          wget https://github.com/HepLib/download/raw/main/usr.tar.gz
          echo Step 1
          ls
          tar zxfv usr.tar.gz
          echo Step 2
          ls
          cmake -DCMAKE_INSTALL_PREFIX=$PWD/usr .
          make -j 4
