on:
  push:
    branches:
    - master

jobs:
  ubuntu-codecoverage:
    name: Ubuntu GCC, Code Coverage (x10)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4      
      - name: "build check"
        run: |
          wget https://github.com/HepLib/download/raw/main/usr.tar.gz
          tar zxfv usr.tar.gz
          cmake -DCMAKE_INSTALL_PREFIX=$PWD/usr .
          make -j 4 install
          wget https://heplib.github.io/src/trace.cpp
          $PWD/usr/bin/heplib++ -o trace trace.cpp
          ./trace
