on:
  push:
    branches:
    - master

jobs:
  ubuntu-codecoverage:
    name: Ubuntu GCC, Code Coverage (x10)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4      
      - name: "build check"
        run: |
          CWD=$PWD
          wget https://heplib.github.io/download/Install.tar.gz
          tar Install usr.tar.gz
          cd Install
          INSTALL_PATH=$CWD/usr jn=2 ./install.sh
          cd $CWD
          cmake -DCMAKE_INSTALL_PREFIX=$CWD/usr .
          make -j 2 install
          wget https://heplib.github.io/src/trace.cpp
          $CWD/usr/bin/heplib++ -o trace trace.cpp
          ./trace
          
