on:
  push:
    branches:
    - main
    - release/*

jobs:
  ##############################################################################
  # ubuntu, gcc, code coverage
  ##############################################################################
  ubuntu-codecoverage:
    name: Ubuntu GCC, Code Coverage (x10)

    runs-on: ubuntu-latest

    steps:
      - name: "Setup"
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          sudo apt-get install -y fig2dev
          sudo apt-get install -y texinfo
          sudo apt-get install -y libcln-dev
          sudo apt-get install -y byacc
          sudo apt-get install -y g++
          sudo apt-get install -y gfortran
          sudo apt-get install -y cmake
          sudo wget https://heplib.github.io/download/Install.tar.gz
          sudo tar xfv Install.tar.gz
          sudo cd Install
          sudo INSTALL_PATH=/usr/local jn=4 ./install.sh
          sudo cd ..
          sudo cmake .
          sudo make -j 4

