on:
  push:
    branches:
    - master

jobs:
  ubuntu-codecoverage:
    name: Ubuntu GCC, Code Coverage (x10)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: doxygen
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REF: github.com/HepLib/doxygen.git
          MYEMAIL: f.feng@outlook.com
          MYNAME: F. Feng          
        run: |
          sudo apt-get install -y doxygen
          echo $PWD
          cd doc
          doxygen
          cd html
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}"
          git init
          git remote add origin https://${REF}
          git add . 
          git commit -m "Updated By Github Actions With Build For Github Pages"
          git branch -M master
          echo start push
          git push --force --quiet "https://${TOKEN}@${REF}"
          echo push done
      
      - name: "Setup"
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          sudo apt-get install -y fig2dev
          sudo apt-get install -y texinfo
          sudo apt-get install -y libcln-dev
          sudo apt-get install -y byacc
          sudo apt-get install -y g++
          sudo apt-get install -y gfortran
          sudo apt-get install -y cmake
          wget https://heplib.github.io/download/Install.tar.gz
          tar xfv Install.tar.gz
          cd Install
          sudo mkdir /usr/local/heplib
          sudo chmod a+rwx /usr/local/heplib
          INSTALL_PATH=/usr/local/heplib jn=4 ./install.sh
          cd ..
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local/heplib .
          make -j 4

