on:
  push:
    branches:
    - master

jobs:
  ##############################################################################
  # ubuntu, gcc, code coverage
  ##############################################################################
  ubuntu-codecoverage:
    name: Ubuntu GCC, Code Coverage (x10)

    runs-on: ubuntu-latest

    steps:
      - name: "Setup"
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          sudo apt-get install -y fig2dev
          sudo apt-get install -y texinfo
          sudo apt-get install -y libcln-dev
          sudo apt-get install -y byacc
          sudo apt-get install -y g++
          sudo apt-get install -y gfortran
          sudo apt-get install -y cmake
          wget https://heplib.github.io/download/Install.tar.gz
          tar xfv Install.tar.gz
          cd Install
          INSTALL_PATH=/usr/local jn=4 ./install.sh
          cd ..
          cmake .
          make -j 4

